name: Documentation Check Before Merge

on:
  pull_request:
    branches:
      - main

jobs:
  check-docstrings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install flake8 flake8-docstrings

      - name: Run Documentation Checks
        run: |
          flake8 --select=D sample.py

